#define GPIO_FELICA_I2C_SCL		51
#define GPIO_FELICA_I2C_SDA		52
#define GPIO_FELICA_UART_RX		28
#define GPIO_FELICA_UART_TX		27
#define GPIO_FELICA_PON			131
#define GPIO_FELICA_RFS			63
#define GPIO_FELICA_HSEL		49
#define GPIO_FELICA_INTU		18
