ccflags-y += -Idrivers/media/platform/msm/camera_ll
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
