
obj-$(CONFIG_ADSP_FACTORY) += adsp_factory.o
#obj-$(CONFIG_MPU6500_FACTORY) += mpu6500_accel.o
#obj-$(CONFIG_MPU6500_FACTORY) += mpu6500_gyro.o
obj-$(CONFIG_MPU6515_FACTORY) += mpu6515_accel.o
obj-$(CONFIG_MPU6515_FACTORY) += mpu6515_gyro.o
obj-$(CONFIG_HSCDTD008A_FACTORY) += hscdtd008a_mag.o
obj-$(CONFIG_GP2AP30_FACTORY)  += gp2ap30_light.o
obj-$(CONFIG_GP2AP30_FACTORY)  += gp2ap30_proximity.o
obj-$(CONFIG_BMA250_FACTORY)   += bma250_accel.o
obj-$(CONFIG_YAS532_FACTORY)   += yas532_mag.o

