# drivers/video/msm/mhl_v2/Makefile
#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 		http://www.samsung.com/

obj-$(CONFIG_VIDEO_MHL_SII8246) += sii8246/
obj-$(CONFIG_VIDEO_MHL_V2) += sii8240/
