obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery.o
ifeq ($(CONFIG_OF),y)
obj-$(CONFIG_ARCH_MSM8974)		+= sec_board-msm8974.o
obj-$(CONFIG_ARCH_MSM8226)		+= sec_board-msm8226.o
obj-$(CONFIG_ARCH_MSM8610)		+= sec_board-msm8610.o
endif
obj-$(CONFIG_FUELGAUGE_MAX17042)	+= max17042_fuelgauge.o	sec_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17048)	+= max17048_fuelgauge.o	sec_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17050)	+= max17050_fuelgauge.o	sec_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX77823)	+= max77823_fuelgauge.o

obj-$(CONFIG_CHARGER_MAX8903)	+= max8903_charger.o
obj-$(CONFIG_CHARGER_SMB328)	+= smb328_charger.o
obj-$(CONFIG_CHARGER_SMB347)	+= smb347_charger.o
obj-$(CONFIG_CHARGER_SMB358)	+= smb358_charger.o
obj-$(CONFIG_CHARGER_SMB1357)	+= smb1357_charger.o
obj-$(CONFIG_CHARGER_BQ24157)	+= bq24157_charger.o sec_charger.o
obj-$(CONFIG_CHARGER_BQ24190)	+= bq24190_charger.o
obj-$(CONFIG_CHARGER_BQ24191)	+= bq24190_charger.o
obj-$(CONFIG_CHARGER_BQ24260)	+= bq24260_charger.o
obj-$(CONFIG_CHARGER_MAX77693)	+= max77693_charger.o
obj-$(CONFIG_CHARGER_MAX77803)	+= max77803_charger.o
obj-$(CONFIG_CHARGER_MAX77804K)	+= max77804k_charger.o
obj-$(CONFIG_CHARGER_MAX77888)  += max77888_charger.o
obj-$(CONFIG_CHARGER_MAX77823)	+= max77823_charger.o
obj-$(CONFIG_CHARGER_SM5414)	+= sm5414_charger.o
