ccflags-y += -Idrivers/media/platform/msm/camera_ll
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
