ccflags-y += -Idrivers/media/platform/msm/camera_ll
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
