ccflags-y += -Idrivers/media/platform/msm/camera_ll
ccflags-y += -Idrivers/media/platform/msm/camera_ll/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
