ifeq ($(CONFIG_ISDBT_FC8150),y)

DRV_NAME = isdbt_fc8150

#EXTRA_CFLAGS += -DDLOG


obj-$(CONFIG_ISDBT_FC8150) += fc8150.o bbm.o fc8150_bb.o fci_tun.o fci_hal.o fci_i2c.o fc8150_i2c.o fc8150_spi.o fc8150_spib.o fc8150_isr.o fc8150_tun.o  fc8150_ppi.o fc8150_hpi.o fci_oal.o fci_ringbuffer.o fci_bypass.o
#
endif

#ccflags-y += -Idrivers/media/isdbt
