
obj-$(CONFIG_INPUT_WACOM_HL)	+= wacom_i2c.o wacom_i2c_firm.o wacom_i2c_func.o

obj-$(CONFIG_EPEN_WACOM_G5SP)	+= wacom_i2c_flash.o
obj-$(CONFIG_EPEN_WACOM_G9PM)	+= wacom_i2c_flash.o
obj-$(CONFIG_EPEN_WACOM_G9PL)	+= w9002_flash.o
obj-$(CONFIG_EPEN_WACOM_G9PLL)	+= w9002_flash.o
obj-$(CONFIG_EPEN_WACOM_G10PM)	+= w9002_flash.o

