#
# Makefile for external connector class (extcon) devices
#

obj-$(CONFIG_EXTCON)		+= extcon-class.o
obj-$(CONFIG_EXTCON_GPIO)	+= extcon-gpio.o
obj-$(CONFIG_EXTCON_ADC_JACK)	+= extcon-adc-jack.o
obj-$(CONFIG_EXTCON_MAX77693)	+= max77693-muic.o
obj-$(CONFIG_EXTCON_MAX77803)	+= extcon-max77803.o
obj-$(CONFIG_EXTCON_MAX77804K)	+= extcon-max77804k.o
obj-$(CONFIG_EXTCON_MAX8997)	+= extcon-max8997.o
obj-$(CONFIG_EXTCON_ARIZONA)	+= extcon-arizona.o
obj-$(CONFIG_EXTCON_TSU6721)	+= extcon-tsu6721.o
obj-$(CONFIG_EXTCON_FSA9485)	+= extcon-fsa9485.o
