#
# Makefile for the kernel character device drivers.
#
obj-$(CONFIG_ISDBT_FC8300) += fc8300/
obj-$(CONFIG_ISDBT_FC8300_SPI) += fc8300_spi/
obj-$(CONFIG_ISDBT_FC8150) += fc8150/
obj-$(CONFIG_ISDBT_FC8150_SPI) += fc8150_spi/
obj-$(CONFIG_ISDBT_FC8150_HKDI) += fc8150_spi/
