ccflags-y += -Idrivers/media/platform/msm/camera_ll/
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_ll/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_i2c_mux.o msm_camera_spi.o msm_camera_dt_util.o
