obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI)	+= synaptics_i2c_rmi.o rmi_dev.o rmi_f54.o rmi_fw_update.o rmi_db.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI_G)	+= synaptics_i2c_rmi.o rmi_dev.o rmi_f54.o rmi_fw_update.o rmi_db.o rmi_guest.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI_G)     += Multiverse/
