##########################################
# Makefile for MTV222 Device Drivers.
##########################################
ccflags-y += -Idrivers/media/mtv
ccflags-y += -Idrivers/media/mtv/mtv222

obj-y += raontv.o
obj-y += raontv_isdbt.o
obj-y += raontv_rf.o
obj-y += raontv_port.o

